### ISSUE TITLE
Not receiving notification

### ISSUE THREAD

**Issue by amarmathur-nagarro** [vivektak/react-app#101]
When I assign ticket from admin to vivek then I didn't receive any notification. It comes first times but after do some testing it is not coming now.

**Comment by shivdotpy** [comment]
I have tested again.

1. Normal Window where admin logged in
    1.1. Assign a ticket to Vivek
2. Incognito where Vivek user logged in
    2.1. Vivek got the notification

If you face this error again, we will sit and discuss it.
