### ISSUE TITLE
Incorrect data is showing on Job opening screen when navigating from dashboard

### ISSUE THREAD

**Issue by amarmathur-nagarro** [vivektak/react-app#105]
On user dashboard, I click on QA tile which has 0 count
![image](https://user-images.githubusercontent.com/56680387/68094638-a06e2c80-fec8-11e9-8ffc-6e6b1f7a30d1.png)
But on opening page I get data of backend and fullstack
![image](https://user-images.githubusercontent.com/56680387/68094650-c267af00-fec8-11e9-8c21-11838ff6c56a.png)
Either the tile should not be clickable or on opening screen "No records to display" message should come.

**Comment by shivdotpy** [comment]
If there is no job available for the particular type, we are showing all the jobs.
