### ISSUE TITLE
In MyTicket screen instead of showing blank "assign to" show "Self"

### ISSUE THREAD

**Issue by amarmathur-nagarro** [vivektak/react-app#85]
Show "Self" where assign to is blank

![image](https://user-images.githubusercontent.com/56680387/67261495-8727b200-f4be-11e9-948e-cf6b72689009.png)

**Comment by vivektak** [comment]
@shivdotpy  please add head hr in the list of all hr.
@amarmathur-nagarro we are going to show HR name instead of any blank space.

**Comment by shivdotpy** [comment]
Done
