### ISSUE TITLE
Incorrect Job ID is showing in My Tickets screen

### ISSUE THREAD

**Issue by amarmathur-nagarro** [vivektak/react-app#86]
In MyTicket screen Job ID 1 is assign to 3 tickets but there is no Opening with job ID 1.
![image](https://user-images.githubusercontent.com/56680387/67261537-b9391400-f4be-11e9-9c3b-5b217a545c76.png)

**Comment by vivektak** [comment]
@shivdotpy , please check this issue

**Comment by shivdotpy** [comment]
This is referrals created from the screen of my referals.
