### ISSUE TITLE
Data not showing properly in MyTicket page

### ISSUE THREAD

**Issue by amarmathur-nagarro** [vivektak/react-app#97]
I have removed all opening
![image](https://user-images.githubusercontent.com/56680387/67735555-7fba5880-fa2a-11e9-85dc-085847b27c3a.png)

But still I can see referral with Job ID
![image](https://user-images.githubusercontent.com/56680387/67735572-91036500-fa2a-11e9-8704-9641bcb81ed9.png)

which make our data inconsistent.

**Comment by shivdotpy** [comment]
Now it will not come because a user cannot delete a job if referral associated with it.
